name: Build and Test PublisherService

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore ./PublisherService/PublisherService.csproj

    - name: Build
      run: dotnet build ./PublisherService/PublisherService.csproj --no-restore

    - name: Build Docker image
      run: docker build -t publisherservice ./PublisherService
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_NAME: ${{ secrets.DB_NAME }}